[All]
Window = "#EFF0F1"
WindowText = "#232629"
Base = "#FFFFFF"
AlternateBase = "#E3E5E7"
ToolTipBase = "#F7F7F7"
ToolTipText = "#232629"
PlaceholderText = "#707D8A"
Text = "#232629"
Button = "#FCFCFC"
ButtonText = "#232629"
# BrightText = ""
Highlight = "#232629"
HighlightedText = "#FFFFFF"
# Accent = ""
