# Taken from https://draculatheme.com/spec

[All]
Window          = "#282A36"     # Background
WindowText      = "#F8F8F2"     # Foreground

Base            = "#282A36"     # Background
Text            = "#F8F8F2"     # Foreground

AlternateBase   = "#343746"     # Floating interactive elements

Button          = "#282A36"     # Background
ButtonText      = "#F8F8F2"     # Foreground

ToolTipBase     = "#282A36"     # Background
ToolTipText     = "#F8F8F2"     # Foreground

Highlight       = "#44475A"     # Selection
HighlightedText = "#F8F8F2"     # Foreground

PlaceholderText = "#6272A4"     # Comment

Accent          = "#BD93F9"     # Purple
